<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>blink_o_mat</RootNamespace>
    <AssemblyName>Rejector</AssemblyName>
    <Product>Rejector</Product>
    <Title>Rejector</Title>
    <ApplicationIcon>Icon\6dd39f16-9f8b-454e-86c4-b44c409cb647.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NETStdFITS" Version="3.0.271" />
    <PackageReference Include="XisfSharp" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BenchmarkSuite1\**" />
    <None Remove="BenchmarkSuite1\**" />
    <Content Remove="BenchmarkSuite1\**" />
    <EmbeddedResource Remove="BenchmarkSuite1\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="6dd39f16-9f8b-454e-86c4-b44c409cb647.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="6dd39f16-9f8b-454e-86c4-b44c409cb647.png" />
  </ItemGroup>

</Project>
