<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Rejector.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="XisfSharp" Version="1.0.2" />
  </ItemGroup>

</Project>
